### ISSUE TITLE
index error when mode=None in `detect_badsegments`

### ISSUE THREAD

**Issue by yingjoeyzhou** [OHBA-analysis/osl#244]
The following config
```
config = """
    preproc:
    - filter: {l_freq: 0.25, h_freq: 125, method: iir, iir_params: {order: 5, ftype: butter}}
    - notch_filter: {freqs: 50 100}
    - resample: {sfreq: 250}
    - bad_segments: {segment_len: 500, picks: mag, significance_level: 0.1}
    - bad_segments: {segment_len: 500, picks: grad, significance_level: 0.1}
    - bad_segments: {segment_len: 500, picks: mag, mode: diff, significance_level: 0.1}
    - bad_segments: {segment_len: 500, picks: grad, mode: diff, significance_level: 0.1}
    - bad_channels: {picks: mag, significance_level: 0.1}
    - bad_channels: {picks: grad, significance_level: 0.1}
    - ica_raw: {picks: meg, n_components: 0.99}
    - ica_autoreject: {picks: meg, ecgmethod: ctps, eogthreshold: auto}
    - interpolate_bads: {}
"""
```

returned the following error
```
index 167749 is out of bounds for axis 0 with size 153001
  File "/home/zhouj/osl/osl/preprocessing/batch.py", line 737, in run_proc_chain
    dataset = func(dataset, userargs)
  File "/home/zhouj/osl/osl/preprocessing/osl_wrappers.py", line 355, in run_osl_bad_segments
    dataset["raw"] = detect_badsegments(dataset["raw"], **userargs)
  File "/home/zhouj/osl/osl/preprocessing/osl_wrappers.py", line 177, in detect_badsegments
    onsets_secs = raw.first_samp/raw.info["sfreq"] + XX_times[onsets.astype(int)]
```

And I tried running the same code with this config (i.e., removed the bad segment detection using `mode=None`)
```
config = """
    preproc:
    - filter: {l_freq: 0.25, h_freq: 125, method: iir, iir_params: {order: 5, ftype: butter}}
    - notch_filter: {freqs: 50 100}
    - resample: {sfreq: 250}
    - bad_segments: {segment_len: 500, picks: mag, mode: diff, significance_level: 0.1}
    - bad_segments: {segment_len: 500, picks: grad, mode: diff, significance_level: 0.1}
    - bad_channels: {picks: mag, significance_level: 0.1}
    - bad_channels: {picks: grad, significance_level: 0.1}
    - ica_raw: {picks: meg, n_components: 0.99}
    - ica_autoreject: {picks: meg, ecgmethod: ctps, eogthreshold: auto}
    - interpolate_bads: {}
"""
```

the preprocessing was successful! 

I have slacked @matsvanes and the data to reproduce this bug is in a temporal folder `4Mats` under `knobre` on hbaws.
